### ISSUE TITLE
Create dynamic charts in the bootcamp to show where time in the bootcamp is spent

### ISSUE THREAD

**Issue by jburns24** [liatrio/devops-bootcamp#276]
There has been an effort to get an idea of what is covered in the bootcamp. At a high level we want to know roughly how long the bootcamp takes and what technologies and categories are covered. Initially I was going the route of putting this in a google sheet which works for quick and dirty stuff but ultimately we want this information to be shared with the world and talked about putting this in a blog post. 

This kind of sucks as the blog post will not age well. Instead we should come up with a dynamic way to put this metadata in the bootcamp and have visualizations generated on the bootcamp

**Comment by jburns24** [comment]
Feature branch for this ticket https://github.com/liatrio/devops-bootcamp/tree/add-dynamic-metrics

Rough outline of the things required for this ticket:
- Sensible way to codify the metadata
- Easy way to retrieve the metadata
- Add bundler so npm packages can be leveraged client side
- Convert deploy process for bootcamp to a custom github action
- Add charts to visualize the data

**Comment by jburns24** [comment]
At the time of writing this comment I will document the choices I made for the above bullet points and the work left to be done.

### Sensible way to codify the metadata
My primary objectives with this goal was to ensure that the metadata lived in a place that was 1. Easy to fetch for the frontend 2. Easy to maintain. With those two goals in mind I ended up with the following system.

Metadata is codified as 'front-matter' which is essentially embedded yaml at the top of each markdown file.

Metadata lives in each section of the bootcamp that needs it. This keeps it locally scoped to a single section/sub-section. This will be in a developers face when they are touching those files and I hope will make them less likely to be forgotten.


### Easy way retrieve the metadata

There is a precommit hook that aggregates all the partial metadata into a sorted 'master record' that lives on the root markdown document `README.md`. Having an aggregated list here gives us a single location to fetch the metadata as apposed to fetching from scattered locations at runtime in which the locations would have to be known to the frontend in some what. 

* This choice of having putting the aggregated metadata on the README.md does mean that stats will require that page to load before they can show. As of now I was going to put these statistics on that page which means this will not be an issue. But if we want to move stats to another page this will be an issue. 

### Add bundler so npm packages can be leveraged client side

This requirement came up as I was developing. Given that this project was pretty simple most js libraries were loaded via Browser Bundles at runtime. When adding metrics (specifically chartjs-wordcloud-plugin) I found there were no published bundles. Which left us the option of minifiying and hosting on a CND or including a bundler like webpack. I opted for the latter as it will allow us to use any npm package we want in the front end, it will allow us to get the benefit of 'tree shaking' and minification in prod resulting in a smaller js bundles being downloaded and should result in a better lighthouse score. 

### Convert deploy process for bootcamp to a custom github action

After making the choice to add a bundler it was then required that we have a `build` step in our deploy pipeline. So we needed to move away from the black box GitHub Pages deploy to a custom GHA deploy. The initial conversion of this has been done but the build step will be added with this feature branch.

### Add charts to visualize the data

The visualizations I am targeting for the first round of this PR are
* WordCloud of the technologies we use. This will give a good landscape of the types of tech that occur most through the bootcamp
* Visualize the percent of time spent in each DevOps 'category' (ie: Containerization, IaC, etc).


## ToDo

- [ ] Add build step to GHA
- [ ] Add visualization of the percent of time spent in each DevOps category
- [ ] Fix wordcloud so it isnt tiny
