### ISSUE TITLE
Continious Testing Project

### ISSUE THREAD

**Issue by botaliatrio** [liatrio/devops-bootcamp#293]
```[tasklist]
### Tasks

Learn basics of Python
***UPD***
\*Installed Anaconda/Jupyter Notebook
\*Learning the basic commands
Learn how to write a REST API with Python
Learn how to write unit tests
Learn how create a local webpage that interacts with your REST API
Could be as simple as "click a button" and show the payload (response) to the screen
Learn how to write integration tests to test your local web page
Learn how to write a simple performance test scenario for your endpoint (using something like locust or k6)

- [x] Learn basics of Python
- [ ] Learn how to write a REST API with Python
- [ ] Learn how to write unit tests
- [ ] Learn how create a local webpage that interacts with your REST API
- [ ] Learn how to write integration tests to test your local web page
- [ ] Learn how to write a simple performance test scenario for your endpoint (using something like locust or k6)
```

**Comment by botaliatrio** [comment]
#4 Could be as simple as "click a button" and show the payload (response) to the screen

**Comment by botaliatrio** [comment]
***UPD***
*Installed Anaconda/Jupyter Notebook
*Learning the basic commands

**Comment by dreweth** [comment]
We descoped this project in lieu of project o11y.  Closing this ticket.
